name: 'Strip and run UPX on executables'
description: 'Dramatically decreases size of executables by stripping them of debug symbols and running UPX on them'
author: 'Sven-Hendrik Haase'
branding:
  icon: file-minus
  color: blue
inputs:
  file:
    description: 'Local file to pack'
    required: true
  args:
    description: 'Arguments to pass to UPX'
  strip:
    description: 'Whether or not "strip" symbols from object file'
    default: 'true'
  strip_args:
    description: 'Arguments to pass to strip'
runs:
  using: 'node12'
  main: 'lib/main.js'
